// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEdLaiPQLOW7rBcn8c4864l8NisqsdQJg',
    appId: '1:209182558820:web:14128225e81e3a38a92d71',
    messagingSenderId: '209182558820',
    projectId: 'poll-76c46',
    authDomain: 'poll-76c46.firebaseapp.com',
    storageBucket: 'poll-76c46.firebasestorage.app',
    measurementId: 'G-3Z2924XH0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqVEZQxcVYkfdekcs0jT7LKAjHTXSz9qs',
    appId: '1:209182558820:android:932616d4d0b7faeda92d71',
    messagingSenderId: '209182558820',
    projectId: 'poll-76c46',
    storageBucket: 'poll-76c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2bwYSVwvTFP1K_U62R_OUE0GM-0gHB0',
    appId: '1:209182558820:ios:d615d4790c395b92a92d71',
    messagingSenderId: '209182558820',
    projectId: 'poll-76c46',
    storageBucket: 'poll-76c46.firebasestorage.app',
    iosClientId: '209182558820-6clvmg4cs7eeu25f3kq6r6v7q0ghdpak.apps.googleusercontent.com',
    iosBundleId: 'com.pollit.app.pollit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2bwYSVwvTFP1K_U62R_OUE0GM-0gHB0',
    appId: '1:209182558820:ios:d615d4790c395b92a92d71',
    messagingSenderId: '209182558820',
    projectId: 'poll-76c46',
    storageBucket: 'poll-76c46.firebasestorage.app',
    iosClientId: '209182558820-6clvmg4cs7eeu25f3kq6r6v7q0ghdpak.apps.googleusercontent.com',
    iosBundleId: 'com.pollit.app.pollit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEdLaiPQLOW7rBcn8c4864l8NisqsdQJg',
    appId: '1:209182558820:web:14128225e81e3a38a92d71',
    messagingSenderId: '209182558820',
    projectId: 'poll-76c46',
    authDomain: 'poll-76c46.firebaseapp.com',
    storageBucket: 'poll-76c46.firebasestorage.app',
    measurementId: 'G-3Z2924XH0M',
  );
}
